services:
  - type: web
    name: mypadicare
    env: python
    pythonVersion: "3.12.7"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000

